apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgres
# The Pod Template (The Blueprint)
  template:
    metadata:
      labels:
        app: immich-postgres
    spec:
      containers:
      # Postgres
      - name: postgres
        image: tensorchord/pgvecto-rs:pg14-v0.2.0
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: immich-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: immich-db-secret
              key: POSTGRES_DB
        volumeMounts:
        - name: immich-db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: immich-db-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
spec:
  selector:
    app: immich-postgres
  ports:
    - port: 5432
      targetPort: 5432